version: '3'
services:
  db:
    image: postgres
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    env_file: ./.env
    build: .
    volumes:
      - .:/bookshelf-web
      - tmp-data:/bookshelf-web/tmp
      - public-data:/bookshelf-web/public
    ports:
      - "3000:3000"
    environment:
      - "RAILS_ENV=${RAILS_ENV}"
    depends_on:
      - db
  nginx:
    build: containers/nginx
    volumes:
      - tmp-data:/bookshelf-web/tmp
      - public-data:/bookshelf-web/public
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  db-data:
    external: true
  tmp-data:
    external: true
  public-data:
    external: true
