version: '3'
services:
  db:
    env_file: ./.env
    image: mysql
    entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_USER=${DB_USERNAME}"
      - MYSQL_ALLOW_EMPTY_PASSWORD='yes'
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  web:
    env_file: ./.env
    build: .
    volumes:
      - .:/bookshelf-web
      - tmp-data:/bookshelf-web/tmp
      - public-data:/bookshelf-web/public
    ports:
      - "3000:3000"
    environment:
      - "RAILS_ENV=${RAILS_ENV}"
    depends_on:
      - db
  nginx:
    build: containers/nginx
    volumes:
      - tmp-data:/bookshelf-web/tmp
      - public-data:/bookshelf-web/public
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
volumes:
  db-data:
    external: true
  tmp-data:
    external: true
  public-data:
    external: true