version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4-alpine
    working_directory: ~/repo
    steps:
      - setup_remote_docker:
          reusable: true
      - run:
          name: システム依存関係のインストール
          command: apk add --update --no-cache linux-headers git sudo openssh-client tar gzip build-base tzdata postgresql-dev nodejs
      - checkout
      - restore_cache:
          name: Bundleキャッシュの復元
          keys:
            - gems-{{ .Environment.CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
            - gems-{{ .Environment.CACHE_KEY }}-
      - run:
          name: Ruby依存関係のインストール
          command: bundle check || bundle install --jobs=4 --retry=3
      - save_cache:
          name: Bundleキャッシュの保存
          key: gems-{{ .Environment.CACHE_KEY }}-{{ checksum "Gemfile.lock" }}
          paths:
            - /usr/local/bundle
      - run:
          name: Rspecの実行
          command: docker-compose up -d web && docker-compose run --rm web rspec
      - add_ssh_keys:
          fingerprints:
            - "8c:1d:91:8e:6f:81:97:55:ef:ac:a8:02:26:77:45:dd"
      - run:
          name: ssh-agent設定
          command: |
            ssh-agent -s > ~/.ssh_agent_conf
            source ~/.ssh_agent_conf
            chmod -R 700 ${HOME}
            for _k in $(ls ${HOME}/.ssh/id*); do
              ssh-add ${_k} || true
            done
            cat <<EOF >> ${HOME}/.ssh/config
              Host github github.com
                HostName github.com
                IdentityFile ~/.ssh/id_rsa_8c1d918e6f819755efaca802267745dd
                User git
            EOF      
      - deploy:
         name: Capistranoデプロイ
         command:
           bundle exec cap production deploy --trace